// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

export const supabase = createClient(
  import.meta.env.VITE_SUPABASE_URL,
  import.meta.env.VITE_SUPABASE_ANON_KEY,
  {
    auth: {
      persistSession: true,
      storage: localStorage,
      storageKey: 'easyauto_auth',
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  }
);